//60
//59
//0
//1
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyFileVersion("1.0.59.60")]
[assembly: AssemblyVersion("1.0.59.60")]